# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.memcached_client:
        class: Clivern\Observability\Aggregation\Client\MemcachedClient
        arguments:
            - '%env(MEMCACHED_SERVER_HOST)%'
            - '%env(int:MEMCACHED_SERVER_PORT)%'

    app.graphite_client:
        class: Clivern\Observability\Reporter\GraphiteClient
        arguments:
            - '%env(GRAPHITE_HOST)'
            - '%env(int:GRAPHITE_PORT)%'

    app.metrics_reporter:
        class: Clivern\Observability\Aggregation\MemcachedAggregate
        arguments:
            - '@app.graphite_client'
            - '@app.memcached_client'
            -
                cache_key_prefix: '%env(METRICS_AGGREGATE_KEY)'
                batch_interval: '%env(int:METRICS_BATCH_INTERVAL_IN_SEC)'

    App\EventSubscriber\RequestSubscriber:
        class: App\EventSubscriber\RequestSubscriber
        arguments:
            - '@app.metrics_reporter'

    App\EventSubscriber\ExceptionSubscriber:
        class: App\EventSubscriber\ExceptionSubscriber
        arguments:
            - '@app.metrics_reporter'

    App\EventSubscriber\ResponseSubscriber:
        class: App\EventSubscriber\ResponseSubscriber
        arguments:
            - '@app.metrics_reporter'
